//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public object byName;
        public object byEmail;
        public object byContact;
        public object numberOfPersons;
        public object reserveDateTime;
        public object eventType;
        public object byMessage;

        public int R_Id { get; set; }
        public string D_Date { get; set; }
        public string A_Date { get; set; }
        public Nullable<int> Room_No { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> NoOfPerson { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
