//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_Type
    {
        public Room_Type()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Capacity { get; set; }
        public string Room_Price { get; set; }
        public string Max_Guest { get; set; }
        public Nullable<int> Admin_ID { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual System_Admin System_Admin { get; set; }
    }
}
