//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Room_Id { get; set; }
        public Nullable<int> Room_No { get; set; }
        public string Room_Status { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<int> Room_Type_Id { get; set; }
        public string IsClean { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual System_Admin System_Admin { get; set; }
        public virtual Room_Type Room_Type { get; set; }
    }
}
