//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaago.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Admin
    {
        public System_Admin()
        {
            this.Rooms = new HashSet<Room>();
            this.Room_Type = new HashSet<Room_Type>();
        }
    
        public int Admin_ID { get; set; }
        public string AdminName { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Room_Type> Room_Type { get; set; }
    }
}
